### PR TITLE
Add support for Intel based MacOS and Windows 

### LINKED ISSUE #68: Support more architectures (via sentry cli)
Currently we are only supporting MacArm and LinuxX86 because of the cli we download.
Actually there are more cli types available to download... We should do that.

### PR DESCRIPTION
**Pull request by Fabi755**
Fixes #68

### CODE REVIEW

**Comment by StefMa** [comment]
Hey @Fabi755 ,

thanks for the contribution ☺.
Could you maybe use the universal version of the cli for macOS?! 
Please also add the windows version so we can close #68

**Comment by Fabi755** [comment]
I'm not really sure, if the Windows implementation is correct. I have orientated on the Sentry [install script](https://github.com/getsentry/sentry-cli/blob/54cde67e9180db8bd0fab72843f6094df04d8e04/scripts/install.js#L63).

**Comment by StefMa** [comment]
Thanks. I think this is good enough.
Did you tested it with the universal cli? 😁

**Comment by Fabi755** [comment]
> Did you tested it with the universal cli? 😁

Yes, with my Intel Chip MacBook it works :-)

**Pull request merged**
